[workspace]
resolver = "2"
members = [
    "crates/system-tools-core",
    "crates/packtide",
    "crates/systide",
    "tools/package-manager-matrix",
]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
version = "0.1.0"
rust-version = "1.88"

[profile.release]
lto = "thin"
codegen-units = 8
strip = "symbols"
panic = "abort"
